version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: pgVector-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=vector_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: "bridge"
